import { createDemoProject } from "../src/lib/show/defaultProject";
import { makeFormation } from "../src/lib/show/formations";
import { addObject, emptyScene, patchObjectTransform } from "../src/lib/show/scene";
import { buildShowPlan } from "../src/lib/show/trajectory/schedule";
import { clipPhase } from "../src/lib/show/types";
const base = createDemoProject(48);
const fa = makeFormation("f-a","Left Wing","grid",24,base.area);
const fb = makeFormation("f-b","Right Wing","circle",24,base.area);
const wa: any = { ...base, formations: [...base.formations, fa, fb] };
const clip = wa.timeline.find((c:any)=>clipPhase(c)==="SHOW");
let scene = emptyScene(clip.id,"Wings");
const f = addObject(wa, scene, { source:{kind:"STATIC",formationId:fa.id}, name:"Left Wing"}); scene=f.scene;
const s2 = addObject(wa, scene, { source:{kind:"STATIC",formationId:fb.id}, name:"Right Wing"}); scene=s2.scene;
scene = patchObjectTransform(scene, f.objectId, {position:[-25,40,0]});
scene = patchObjectTransform(scene, s2.objectId, {position:[25,40,0]});
const project = { ...wa, scenes:[scene] };
const plan = buildShowPlan(project);
console.log(clip.id, f.objectId, s2.objectId);
console.log(JSON.stringify(plan.participation.find((p:any)=>p.clipId===clip.id)?.activeGroups?.map((g:any)=>({g:g.groupId,i:g.instanceId,n:g.droneIndices?.length}))));
